/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_portfolio_ewhitaker_SysCall */

#ifndef _Included_io_portfolio_ewhitaker_SysCall
#define _Included_io_portfolio_ewhitaker_SysCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_portfolio_ewhitaker_SysCall
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_portfolio_ewhitaker_SysCall_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
