/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_portfolio_ewhitaker_system_SystemCall */

#ifndef _Included_io_portfolio_ewhitaker_system_SystemCall
#define _Included_io_portfolio_ewhitaker_system_SystemCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_open__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    open
 * Signature: (Ljava/lang/String;IJ)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_open__Ljava_lang_String_2IJ
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    stat
 * Signature: (Ljava/lang/String;)Lio/portfolio/ewhitaker/system/file/FileStatistic;
 */
JNIEXPORT jobject JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_stat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    fstat
 * Signature: (I)Lio/portfolio/ewhitaker/system/file/FileStatistic;
 */
JNIEXPORT jobject JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_fstat
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    getdents
 * Signature: (IJ)[Lio/portfolio/ewhitaker/system/file/DirectoryEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_getdents
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    mkdir
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_mkdir
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    creat
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_creat
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
