/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_portfolio_ewhitaker_system_SystemCall */

#ifndef _Included_io_portfolio_ewhitaker_system_SystemCall
#define _Included_io_portfolio_ewhitaker_system_SystemCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    creat
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_creat
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     io_portfolio_ewhitaker_system_SystemCall
 * Method:    mkdir
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_io_portfolio_ewhitaker_system_SystemCall_mkdir
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
